name: Deploy para GitHub Pages

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v4

      - name: Verificar se public/index.html existe
        run: |
          if [ ! -f public/index.html ]; then
            echo "Erro: public/index.html não encontrado!"
            exit 1
          fi

      - name: Configurar Node.js (opcional)
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Publicar conteúdo da pasta public/ no GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
