name: Verificar index.html antes do deploy

on:
  push:
    branches:
      - main

jobs:
  verificar-index:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v4

      - name: Verificar se public/index.html existe
        run: |
          if [ ! -f public/index.html ]; then
            echo "Erro: public/index.html não encontrado!"
            exit 1
          fi
